init: &init
  docker:
    - image: docksal/ci-agent:1.2-php
  working_directory: ~/build
  environment:
      BASH_ENV: /home/agent/.bashrc

run-envvars: &run-envvars
  name: Configuring build environment
  command: |
    env

run-sandbox: &run-sandbox
  name: Sandbox provisioning
  command: |
    env

version: 2
jobs:
  sandbox:
    <<: *init
    steps:
      - run:
          <<: *run-envvars
      - checkout
      - run:
          <<: *run-sandbox

workflows:
  version: 2
  default-workflow:
    jobs:
      - sandbox:
