init: &init
  docker:
    - image: docksal/ci-agent:1.2-php
  working_directory: ~/build
  environment:
      BASH_ENV: /home/agent/.bashrc

run-sandbox: &run-sandbox
  name: Sandbox provisioning
  command: |
    export DOMAIN=`echo $DOMAIN | tr "[:upper:]" "[:lower:]"`
    echo 'DOMAIN='"$DOMAIN" >> $BASH_ENV
    build-init
    ssh docker-host "cd $REMOTE_BUILD_DIR && fin init"

version: 2
jobs:
  sandbox:
    <<: *init
    steps:
      - checkout
      - run:
          <<: *run-sandbox

workflows:
  version: 2
  default-workflow:
    jobs:
      - sandbox:
